namespace Fm2ndParser
{
    public class KGTBuiltInSkills
    {
        public uint None { get; set; }
        public uint HitLetterHit { get; set; }
        public uint HitNumber0 { get; set; }
        public uint HitNumber1 { get; set; }
        public uint HitNumber2 { get; set; }
        public uint HitNumber3 { get; set; }
        public uint HitNumber4 { get; set; }
        public uint HitNumber5 { get; set; }
        public uint HitNumber6 { get; set; }
        public uint HitNumber7 { get; set; }
        public uint HitNumber8 { get; set; }
        public uint HitNumber9 { get; set; }
        public uint OffsetHitMark { get; set; }
        public uint RoundAniStarttime { get; set; }
        public uint RoundAniEndtime { get; set; }
        public uint Round1 { get; set; }
        public uint Round2 { get; set; }
        public uint Round3 { get; set; }
        public uint Round4 { get; set; }
        public uint Round5 { get; set; }
        public uint Round6 { get; set; }
        public uint Round7 { get; set; }
        public uint Round8 { get; set; }
        public uint Round9 { get; set; }
        public uint RoundFinal { get; set; }
        public uint Spirits { get; set; }
        public uint KO { get; set; }
        public uint Perfect { get; set; }
        public uint YouWin { get; set; }
        public uint YouLose { get; set; }
        public uint P1Wins { get; set; }
        public uint P2Wins { get; set; }
        public uint Draw { get; set; }
        public uint DoubleKo { get; set; }
        public uint UnlimitedSign { get; set; }
        public uint TimeNumber0 { get; set; }
        public uint TimeNumber1 { get; set; }
        public uint TimeNumber2 { get; set; }
        public uint TimeNumber3 { get; set; }
        public uint TimeNumber4 { get; set; }
        public uint TimeNumber5 { get; set; }
        public uint TimeNumber6 { get; set; }
        public uint TimeNumber7 { get; set; }
        public uint TimeNumber8 { get; set; }
        public uint TimeNumber9 { get; set; }
        public uint VictoryMarkOn { get; set; }
        public uint VictoryMarkOff { get; set; }
        public uint StageLayout1 { get; set; }
        public uint StageLayout2 { get; set; }
        public uint StageLayout3 { get; set; }
        public uint StageLayout4 { get; set; }
        public uint StageLayout5 { get; set; }
        public uint StageLayout6 { get; set; }
        public uint StageLayout7 { get; set; }
        public uint StageLayout8 { get; set; }
        public uint StageLayout9 { get; set; }
        public uint StageLayout10 { get; set; }
        public uint P1LifeGauge { get; set; }
        public uint P2LifeGauge { get; set; }
        public uint P1SpecialGauge { get; set; }
        public uint P2SpecialGauge { get; set; }
        public uint PositionTimer { get; set; }
        public uint Pos1pFace { get; set; }
        public uint Pos2pFace { get; set; }
        public uint PosSpecialStock1p { get; set; }
        public uint PosSpecialStock2p { get; set; }
        public uint PosVictoryMark1p { get; set; }
        public uint VPosVictoryMark2p { get; set; }
        public uint TitleCursor { get; set; }
        public uint PositionForStoryMode { get; set; }
        public uint PositionForVsMode { get; set; }
        public uint ContinuteCursor { get; set; }
        public uint PositionCursorItDoes { get; set; }
        public uint PositionCursorItDoesNot { get; set; }
        public uint P1VsScreenCursor { get; set; }
        public uint P2VsScreenCursor { get; set; }
        public uint P1VsScreenCursorAfterInput { get; set; }
        public uint P2VsScreenCursorAfterInput { get; set; }
        public uint PosCursorForTeamBattle { get; set; }
        public uint Pause { get; set; }
        public uint Spare6 { get; set; }
        public uint Spare7 { get; set; }
        public uint Spare8 { get; set; }
        public uint Spare9 { get; set; }
        public uint Spare10 { get; set; }
        public uint Spare11 { get; set; }
        public uint Spare12 { get; set; }
        public uint Spare13 { get; set; }
        public uint Spare14 { get; set; }
        public uint Spare15 { get; set; }
        public uint Spare16 { get; set; }
        public uint Spare17 { get; set; }
        public uint Spare18 { get; set; }
        public uint Spare19 { get; set; }
    }
}