namespace Fm2ndParser.Kgt
{
    public class KGTBuiltInSkills
    {
        public ushort None { get; set; }
        public ushort HitLetterHit { get; set; }
        public ushort HitNumber0 { get; set; }
        public ushort HitNumber1 { get; set; }
        public ushort HitNumber2 { get; set; }
        public ushort HitNumber3 { get; set; }
        public ushort HitNumber4 { get; set; }
        public ushort HitNumber5 { get; set; }
        public ushort HitNumber6 { get; set; }
        public ushort HitNumber7 { get; set; }
        public ushort HitNumber8 { get; set; }
        public ushort HitNumber9 { get; set; }
        public ushort OffsetHitMark { get; set; }
        public ushort RoundAniStarttime { get; set; }
        public ushort RoundAniEndtime { get; set; }
        public ushort Round1 { get; set; }
        public ushort Round2 { get; set; }
        public ushort Round3 { get; set; }
        public ushort Round4 { get; set; }
        public ushort Round5 { get; set; }
        public ushort Round6 { get; set; }
        public ushort Round7 { get; set; }
        public ushort Round8 { get; set; }
        public ushort Round9 { get; set; }
        public ushort RoundFinal { get; set; }
        public ushort Spirits { get; set; }
        public ushort KO { get; set; }
        public ushort Perfect { get; set; }
        public ushort YouWin { get; set; }
        public ushort YouLose { get; set; }
        public ushort P1Wins { get; set; }
        public ushort P2Wins { get; set; }
        public ushort Draw { get; set; }
        public ushort DoubleKo { get; set; }
        public ushort UnlimitedSign { get; set; }
        public ushort TimeNumber0 { get; set; }
        public ushort TimeNumber1 { get; set; }
        public ushort TimeNumber2 { get; set; }
        public ushort TimeNumber3 { get; set; }
        public ushort TimeNumber4 { get; set; }
        public ushort TimeNumber5 { get; set; }
        public ushort TimeNumber6 { get; set; }
        public ushort TimeNumber7 { get; set; }
        public ushort TimeNumber8 { get; set; }
        public ushort TimeNumber9 { get; set; }
        public ushort SpecialStockNumber0 { get; set; }
        public ushort SpecialStockNumber1 { get; set; }
        public ushort SpecialStockNumber2 { get; set; }
        public ushort SpecialStockNumber3 { get; set; }
        public ushort SpecialStockNumber4 { get; set; }
        public ushort SpecialStockNumber5 { get; set; }
        public ushort SpecialStockNumber6 { get; set; }
        public ushort SpecialStockNumber7 { get; set; }
        public ushort SpecialStockNumber8 { get; set; }
        public ushort SpecialStockNumber9 { get; set; }
        public ushort VictoryMarkOn { get; set; }
        public ushort VictoryMarkOff { get; set; }
        public ushort StageLayout1 { get; set; }
        public ushort StageLayout2 { get; set; }
        public ushort StageLayout3 { get; set; }
        public ushort StageLayout4 { get; set; }
        public ushort StageLayout5 { get; set; }
        public ushort StageLayout6 { get; set; }
        public ushort StageLayout7 { get; set; }
        public ushort StageLayout8 { get; set; }
        public ushort StageLayout9 { get; set; }
        public ushort StageLayout10 { get; set; }
        public ushort P1LifeGauge { get; set; }
        public ushort P2LifeGauge { get; set; }
        public ushort P1SpecialGauge { get; set; }
        public ushort P2SpecialGauge { get; set; }
        public ushort PositionTimer { get; set; }
        public ushort Pos1pFace { get; set; }
        public ushort Pos2pFace { get; set; }
        public ushort PosSpecialStock1p { get; set; }
        public ushort PosSpecialStock2p { get; set; }
        public ushort PosVictoryMark1p { get; set; }
        public ushort VPosVictoryMark2p { get; set; }
        public ushort TitleCursor { get; set; }
        public ushort PositionForStoryMode { get; set; }
        public ushort PositionForVsMode { get; set; }
        public ushort ContinuteCursor { get; set; }
        public ushort PositionCursorItDoes { get; set; }
        public ushort PositionCursorItDoesNot { get; set; }
        public ushort P1VsScreenCursor { get; set; }
        public ushort P2VsScreenCursor { get; set; }
        public ushort P1VsScreenCursorAfterInput { get; set; }
        public ushort P2VsScreenCursorAfterInput { get; set; }
        public ushort PosCursorForTeamBattle { get; set; }
        public ushort Pause { get; set; }
        public ushort Spare6 { get; set; }
        public ushort Spare7 { get; set; }
        public ushort Spare8 { get; set; }
        public ushort Spare9 { get; set; }
        public ushort Spare10 { get; set; }
        public ushort Spare11 { get; set; }
        public ushort Spare12 { get; set; }
        public ushort Spare13 { get; set; }
        public ushort Spare14 { get; set; }
        public ushort Spare15 { get; set; }
        public ushort Spare16 { get; set; }
        public ushort Spare17 { get; set; }
        public ushort Spare18 { get; set; }
        public ushort Spare19 { get; set; }
    }
}